_wandb:
    value:
        cli_version: 0.24.2
        e:
            eetdna0c0uxae8p6g7wkr68s37ac29b7:
                codePath: tests\verify_wandb_online.py
                codePathLocal: tests\verify_wandb_online.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "998393245696"
                        used: "283293810688"
                email: jhonatan.davislaitonavendano@gmail.com
                executable: C:\Users\jhona\Documents\Proyectos\Trader Gemini\.venv\Scripts\python.exe
                git:
                    commit: 1930f6a7ef4e72621ac66ab71b93a97fc22564b1
                host: Jhonala
                memory:
                    total: "16518447104"
                os: Windows-11-10.0.26220-SP0
                program: C:\Users\jhona\Documents\Proyectos\Trader Gemini\tests\verify_wandb_online.py
                python: CPython 3.14.2
                root: C:\Users\jhona\Documents\Proyectos\Trader Gemini
                startedAt: "2026-02-11T15:27:39.021487Z"
                writerId: eetdna0c0uxae8p6g7wkr68s37ac29b7
        m: []
        python_version: 3.14.2
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
            "4": 3.14.2
            "5": 0.24.2
            "8":
                - 3
            "10":
                - 20
            "12": 0.24.2
            "13": windows-amd64
phase:
    value: 99_Verification
test_mode:
    value: true
